import styles from './SampleOutputStrip.module.css'

export default function SampleOutputStrip() {
  return (
    <div className={styles.strip}>
      <div className={styles.track}>
        
          href="/sample"
          className={styles.imgLink}
          aria-label="See the full sample proposal — Compliance Cross-Reference Matrix page"
        >
          <img
            src="/images/samples/sample-p2.webp"
            alt="Compliance Cross-Reference Matrix page from a sample proposal generated by the Proposal Builder"
            width="220"
            height="285"
            loading="lazy"
            className={styles.img}
          />
        </a>
        
          href="/sample"
          className={styles.imgLink}
          aria-label="See the full sample proposal — Price Proposal page"
        >
          <img
            src="/images/samples/sample-p5.webp"
            alt="Price Proposal page with CLIN pricing table from a sample proposal generated by the Proposal Builder"
            width="220"
            height="285"
            loading="lazy"
            className={styles.img}
          />
        </a>
        
          href="/sample"
          className={styles.imgLink}
          aria-label="See the full sample proposal — Cover page"
        >
          <img
            src="/images/samples/sample-p1.webp"
            alt="Cover page from a sample proposal generated by the Proposal Builder"
            width="220"
            height="285"
            loading="lazy"
            className={styles.img}
          />
        </a>
      </div>

      <div className={styles.footer}>
        <p className={styles.caption}>
          Actual output. Fictional example company.
        </p>
        <a href="/sample" className={styles.link}>
          See the full sample →
        </a>
      </div>
    </div>
  )
}